---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu-18.04
    image: ubuntu:18.04
    privileged: true
  - name: debian
    image: debian
    privileged: true
  - name: ubuntu-16.04
    image: ubuntu:16.04
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ANSIBLE0013
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - lint
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
    enabled: false
