---
# tasks file for centos7-common
- name: Install htop
  package: name=htop state=present
- name: Install vim
  package: name=vim state=present
- name: Install nginx
  package: name=nginx state=present
- name: Make sure nginx is running and starting at boot
  service: name=nginx state=started enabled=yes
...
